//! # Gemini Audio Generation Example
//!
//! Demonstrates how to use the Google Gemini API to generate audio from text (TTS).
//!
//! ## Usage
//!
//! ```bash
//! export GOOGLE_GENERATIVE_AI_API_KEY=AIza...
//! cargo run --example gemini_audio_generation --features google
//! ```

use qai_sdk::core::types::SpeechOptions;
use qai_sdk::core::SpeechModel;
use qai_sdk::google::create_google;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let api_key = std::env::var("GOOGLE_GENERATIVE_AI_API_KEY")
        .expect("GOOGLE_GENERATIVE_AI_API_KEY must be set");

    let provider = create_google(qai_sdk::core::types::ProviderSettings {
        api_key: Some(api_key),
        ..Default::default()
    });

    // Gemini 2.5 flash is commonly used for multimodal and audio capabilities
    let model = provider.speech_model("gemini-2.5-flash");

    println!("Sending TTS request to Gemini...");

    let options = SpeechOptions {
        model_id: "gemini-2.5-flash".to_string(),
        input: "Hello there! This is a voice generated by Google Gemini using the Q-A-I SDK. Isn't this fantastic?".to_string(),
        voice: "Aoede".to_string(), // Available voices: Puck, Charon, Kore, Fenrir, Aoede
        response_format: None,
        speed: None,
    };

    let result = model.synthesize(options).await?;

    println!("Audio successfully generated!");
    println!("Audio payload size: {} bytes", result.audio.len());

    // Write to a local file for playback
    let filename = "gemini_output.wav";
    std::fs::write(filename, &result.audio)?;
    println!("Saved audio to {}", filename);

    Ok(())
}
